### ISSUE TITLE
No Link

### ISSUE THREAD

**Issue by xaiyadev** [theowoo/agbg#3]
I dont find a link to open the website. And I think nobody want to download this website for him self and then open it.
Or?

**Comment by A1asd** [comment]
click on the `Get New Url` button. It generates a url with your current settings, which you can add as a browser source in your streaming tool.

You can find the button at the bottom of the form:

![grafik](https://user-images.githubusercontent.com/7797606/114273748-a4866e00-9a1b-11eb-941b-5d7a7d4f8242.png)

**Comment by xaiyadev** [comment]
No I mean in the readme That you can click in And you come to the Page where you can make all settings
